# Generated by Django 3.1.7 on 2021-04-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=60)),
                ('lastName', models.CharField(max_length=60)),
                ('userName', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('role', models.CharField(max_length=60)),
            ],
        ),
    ]
